<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zry</groupId>
        <artifactId>xiaohongshu-comment</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xiaohongshu-comment-biz</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>



    <dependencies>

        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-biz-operationlog</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-biz-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Retry 重试框架  -->
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>

        <!-- AOP 切面（Spring Retry 重试框架需要） -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <!-- Rocket MQ 客户端 -->
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-distributed-id-generator-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-kv-api</artifactId>
        </dependency>
        <!-- 快手 Buffer Trigger -->
        <dependency>
            <groupId>com.github.phantomthief</groupId>
            <artifactId>buffer-trigger</artifactId>
        </dependency>
        <!-- Redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-user-api</artifactId>
        </dependency>
        <!-- Caffeine 本地缓存 -->
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>


    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.mybatis.generator</groupId>
                <artifactId>mybatis-generator-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
