storage:
  minio:
    endpoint: http://47.236.36.111:9000
    accessKey: zhaorenyi
    secretKey: 12345678
  aliyun-oss:
    endpoint: http://47.236.36.111:9000
    accessKey: zhaorenyi
    secretKey: 12345678