storage:
  minio:
    endpoint: 
    accessKey: admin
    secretKey: password123
  aliyun-oss:
    # 地域节点
    endpoint: oss-cn-guangzhou.aliyuncs.com
    # 有访问权限的用户的 access-key-id
    accessKey: 
    # 有访问权限的用户的 access-key-Secret
    secretKey: 
spring:
  servlet:
    multipart:
      max-file-size: 300MB      # 单个文件最大大小
      max-request-size: 300MB  # 整个请求最大大小
      enabled: true            # 启用文件上传        # 启用文件上传
