leaf.name=com.sankuai.leaf.opensource.test
leaf.segment.enable=true
leaf.jdbc.url=jdbc:mysql://127.0.0.1:3306/leaf?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
leaf.jdbc.username=root
leaf.jdbc.password=625272

# ???? snowflake ??
leaf.snowflake.enable=true
# snowflake ???? zk ??
leaf.snowflake.zk.address=127.0.0.1:2181
# snowflake ??????????
leaf.snowflake.port=2222

