<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zry</groupId>
        <artifactId>xiaohongshu</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xiaohongshu-search</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>

    <dependencies>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zry</groupId>
            <artifactId>xiaohongshu-spring-boot-starter-biz-operationlog</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>


    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
